In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4],dtype='int32')

In [4]:
b = np.array([1,2,3,4])

In [5]:
type(a)

numpy.ndarray

In [6]:
type(b)

numpy.ndarray

In [7]:
#get dimension
a.ndim

1

In [8]:
a.shape

(4,)

In [16]:
arr = np.array([[1.,2,3,4],[5,6,7,8]])

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.ndim

2

In [13]:
arr.shape

(2, 4)

In [14]:
a.dtype

dtype('int32')

In [17]:
arr.dtype

dtype('float64')

In [18]:
arr

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [19]:
name =np.array(['ram','shyam','sia'])

In [20]:
name.dtype

dtype('<U5')

In [21]:
a.itemsize

4

In [22]:
name.itemsize

20

In [23]:
name.nbytes

60

In [24]:
name.size

3

In [25]:
a.nbytes

16

In [26]:
name

array(['ram', 'shyam', 'sia'], dtype='<U5')

In [29]:
ar = np.arange(0,21)

In [30]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [31]:

ar[1]

1

In [32]:
name[0]

'ram'

In [35]:
#slicing
slar=ar[1:5]

In [36]:
type(slar)

numpy.ndarray

In [38]:
ar[:2]

array([0, 1])

In [39]:
ar[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [40]:
#reverse
ar[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

In [41]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [42]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [43]:
ar[0]=100

In [44]:
ar

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [45]:
arr

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [46]:
arr[1,2]

7.0

In [47]:
arr[0,2::]

array([3., 4.])

In [51]:
arr[0,2::-1]

array([3., 2., 1.])

In [52]:
azeros = np.zeros(5)

In [53]:
azeros

array([0., 0., 0., 0., 0.])

In [54]:
azeros.dtype

dtype('float64')

In [55]:
azero1 = np.zeros((3,3))

In [56]:
azero1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
aones = np.ones((4))

In [58]:
aones

array([1., 1., 1., 1.])

In [59]:
aones2 = np.ones((4,4))

In [60]:
aones2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
aones3= np.ones((4,2,2))

In [62]:
aones3

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [64]:
aones3[1,1,1]

1.0

In [65]:
np.full((2,2),90)

array([[90, 90],
       [90, 90]])

In [66]:
arfull = np.full((4,2,3),-100)

In [67]:
arfull

array([[[-100, -100, -100],
        [-100, -100, -100]],

       [[-100, -100, -100],
        [-100, -100, -100]],

       [[-100, -100, -100],
        [-100, -100, -100]],

       [[-100, -100, -100],
        [-100, -100, -100]]])

In [69]:
azeros

array([0., 0., 0., 0., 0.])

In [70]:
np.full_like(azeros,4)

array([4., 4., 4., 4., 4.])

In [71]:
#random values
arandom = np.random.rand(5)

In [72]:
arandom

array([0.6479565 , 0.20684951, 0.62077301, 0.76098834, 0.6320425 ])

In [73]:
arandom1 = np.random.rand(4,2)

In [74]:
arandom1

array([[0.31799902, 0.67735159],
       [0.02457304, 0.16895057],
       [0.09819939, 0.8674484 ],
       [0.94249228, 0.09927086]])

In [75]:
arrint = np.random.randint(-4,8,size=(3,3))

In [76]:
arrint

array([[ 4,  3,  3],
       [ 7, -1,  3],
       [ 6,  2,  7]])

In [77]:
idmtx = np.identity(5)

In [78]:
idmtx


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
arr1 = np.array([[1,2,3]])

In [81]:
arr1.ndim

2

In [82]:
arr1 = np.array([1,2,3])

In [83]:
arr1.ndim

1

In [84]:
r1=np.repeat(arr1,3,axis=0)

In [85]:
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [87]:
r1=np.repeat(arr1,3,axis=0)

In [88]:
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [89]:
r1=np.repeat(arr1,3,axis=1)

In [90]:
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [92]:
a

array([1, 2, 3, 4])

In [93]:
cp = a.copy()

In [94]:
cp

array([1, 2, 3, 4])

In [95]:
cp[0]=100

In [96]:
cp

array([100,   2,   3,   4])

In [97]:
a

array([1, 2, 3, 4])

In [98]:
a

array([1, 2, 3, 4])

In [99]:
#Mathematics with Arrays
a+2

array([3, 4, 5, 6])

In [100]:
a

array([1, 2, 3, 4])

In [101]:
arr

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [102]:
arr+4

array([[ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [103]:
a-1

array([0, 1, 2, 3])

In [104]:
arr -2

array([[-1.,  0.,  1.,  2.],
       [ 3.,  4.,  5.,  6.]])

In [105]:
a*2

array([2, 4, 6, 8])

In [106]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [107]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [108]:
z= np.array([1,0,1,0])

In [109]:
a

array([1, 2, 3, 4])

In [110]:
z

array([1, 0, 1, 0])

In [111]:
a+z

array([2, 2, 4, 4])

In [112]:
a-b

array([0, 0, 0, 0])

In [113]:
a*z

array([1, 0, 3, 0])

In [114]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [115]:
#Matrix multiplication
a1 =np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [119]:
b = np.full((3,2),10.)

In [120]:
b

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

In [122]:
np.matmul(a1,b)

array([[30., 30.],
       [30., 30.]])

In [123]:
#Statistics

In [124]:
stats = np.array([[1,2,3],[4,5,6]])

In [125]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.min(stats)

1

In [127]:
np.max(stats)

6

In [128]:
np.min(stats,axis=0)

array([1, 2, 3])

In [129]:
np.min(stats,axis=1)

array([1, 4])

In [130]:
np.max(stats,axis=0)

array([4, 5, 6])

In [131]:
np.max(stats,axis=1)

array([3, 6])

In [132]:
np.sum(stats)

21

In [133]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [135]:
np.sum(stats,axis=1)

array([ 6, 15])

In [136]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
after = stats.reshape(3,2)

In [138]:
stats.shape

(2, 3)

In [139]:
after.shape

(3, 2)

In [140]:
after

array([[1, 2],
       [3, 4],
       [5, 6]])

In [142]:
filedat = np.genfromtxt(r'C:\Users\Krishna\data\python_code\dataarr.txt',delimiter=',')

In [143]:
type(filedat)

numpy.ndarray

In [144]:
filedat.shape

(3, 18)

In [145]:
filedat.dtype

dtype('float64')

In [146]:
filedat

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [147]:
np.sum(filedat)

2792.0

In [153]:
res=np.sum(filedat,axis=0)

In [149]:
np.sum(filedat,axis=1)

array([ 394., 1048., 1350.])

In [155]:
np.savetxt(r'C:\Users\Krishna\data\python_code\output.txt',res)